// ====================
// Popular Categories
// ====================


// ====================
// Dummy Products (40+)
// ====================
export const products = [
  // Electronics
  {
    id: 1,
    name: "Sony Headphones",
    type: "electronics",
    price: 3500,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "black",
    material: "plastic",
    brand: "Sony",
    offer: 20,
  },
  {
    id: 2,
    name: "Samsung LED TV",
    type: "electronics",
    price: 18000,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "black",
    material: "metal",
    brand: "Samsung",
    offer: "40",
  },
  {
    id: 3,
    name: "Apple iPhone 14",
    type: "electronics",
    price: 75000,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "white",
    material: "metal",
    brand: "Apple",
    offer: 10,
  },
  {
    id: 4,
    name: "Dell Laptop",
    type: "electronics",
    price: 55000,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "silver",
    material: "metal",
    brand: "Dell",
    offer: 15,
  },
  {
    id: 5,
    name: "Canon DSLR Camera",
    type: "electronics",
    price: 42000,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "black",
    material: "metal",
    brand: "Canon",
    offer: 25,
  },

  // Appliances
  {
    id: 6,
    name: "LG Refrigerator",
    type: "appliances",
    price: 30000,
    image: "https://placehold.co/300x200",
    review: 3,
    color: "white",
    material: "metal",
    brand: "LG",
    offer: 70,
  },
  {
    id: 7,
    name: "Whirlpool Washing Machine",
    type: "appliances",
    price: 25000,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "grey",
    material: "metal",
    brand: "Whirlpool",
    offer: 20,
  },
  {
    id: 8,
    name: "Philips Air Fryer",
    type: "appliances",
    price: 8500,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "black",
    material: "plastic",
    brand: "Philips",
    offer: 15,
  },
  {
    id: 9,
    name: "Bosch Dishwasher",
    type: "appliances",
    price: 40000,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "silver",
    material: "metal",
    brand: "Bosch",
    offer: 30,
  },
  {
    id: 10,
    name: "Samsung Microwave Oven",
    type: "appliances",
    price: 12000,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "black",
    material: "metal",
    brand: "Samsung",
    offer: 25,
  },

  // Furniture
  {
    id: 11,
    name: "Ikea Wooden Table",
    type: "furniture",
    price: 12000,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "brown",
    material: "wood",
    brand: "Ikea",
    offer: 50,
  },
  {
    id: 12,
    name: "Urban Ladder Sofa",
    type: "furniture",
    price: 22000,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "grey",
    material: "fabric",
    brand: "Urban Ladder",
    offer: 20,
  },
  {
    id: 13,
    name: "Godrej Office Chair",
    type: "furniture",
    price: 8000,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "black",
    material: "plastic",
    brand: "Godrej",
    offer: 15,
  },
  {
    id: 14,
    name: "HomeTown Bookshelf",
    type: "furniture",
    price: 9500,
    image: "https://placehold.co/300x200",
    review: 3,
    color: "brown",
    material: "wood",
    brand: "HomeTown",
    offer: 30,
  },
  {
    id: 15,
    name: "Durian Bed Frame",
    type: "furniture",
    price: 28000,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "white",
    material: "wood",
    brand: "Durian",
    offer: 40,
  },

  // Clothing
  {
    id: 16,
    name: "Nike Running Shoes",
    type: "cloth",
    price: 2500,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "red",
    material: "rubber",
    brand: "Nike",
    offer: 10,
  },
  {
    id: 17,
    name: "Adidas T-Shirt",
    type: "cloth",
    price: 1200,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "blue",
    material: "cotton",
    brand: "Adidas",
    offer: 20,
  },
  {
    id: 18,
    name: "Levi’s Jeans",
    type: "cloth",
    price: 3500,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "black",
    material: "denim",
    brand: "Levi’s",
    offer: 15,
  },
  {
    id: 19,
    name: "Puma Jacket",
    type: "cloth",
    price: 4500,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "green",
    material: "cotton",
    brand: "Puma",
    offer: 30,
  },
  {
    id: 20,
    name: "Zara Dress",
    type: "cloth",
    price: 5200,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "white",
    material: "cotton",
    brand: "Zara",
    offer: 25,
  },

  // Cleaning
  {
    id: 21,
    name: "Dettol Floor Cleaner",
    type: "cleaning",
    price: 250,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "green",
    material: "liquid",
    brand: "Dettol",
    offer: 10,
  },
  {
    id: 22,
    name: "Harpic Toilet Cleaner",
    type: "cleaning",
    price: 180,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "blue",
    material: "liquid",
    brand: "Harpic",
    offer: 15,
  },
  {
    id: 23,
    name: "Surf Excel Detergent",
    type: "cleaning",
    price: 600,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "white",
    material: "powder",
    brand: "Surf Excel",
    offer: 20,
  },
  {
    id: 24,
    name: "Vim Dishwash Gel",
    type: "cleaning",
    price: 120,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "yellow",
    material: "liquid",
    brand: "Vim",
    offer: 30,
  },
  {
    id: 25,
    name: "Lizol Floor Cleaner",
    type: "cleaning",
    price: 400,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "pink",
    material: "liquid",
    brand: "Lizol",
    offer: 20,
  },

  // Accessories
  {
    id: 26,
    name: "RayBan Sunglasses",
    type: "accessories",
    price: 6500,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "black",
    material: "plastic",
    brand: "RayBan",
    offer: 20,
  },
  {
    id: 27,
    name: "Titan Wrist Watch",
    type: "accessories",
    price: 8500,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "silver",
    material: "metal",
    brand: "Titan",
    offer: 25,
  },
  {
    id: 28,
    name: "Fossil Smart Watch",
    type: "accessories",
    price: 12000,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "black",
    material: "metal",
    brand: "Fossil",
    offer: 30,
  },
  {
    id: 29,
    name: "Louis Vuitton Handbag",
    type: "accessories",
    price: 50000,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "brown",
    material: "leather",
    brand: "Louis Vuitton",
    offer: 15,
  },
  {
    id: 30,
    name: "Boat Bluetooth Earbuds",
    type: "accessories",
    price: 2200,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "white",
    material: "plastic",
    brand: "Boat",
    offer: 35,
  },

  // (Add ~10 more random products for variety)
  {
    id: 31,
    name: "HP Printer",
    type: "electronics",
    price: 9500,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "white",
    material: "plastic",
    brand: "HP",
    offer: 20,
  },
  {
    id: 32,
    name: "Dyson Vacuum Cleaner",
    type: "appliances",
    price: 32000,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "purple",
    material: "plastic",
    brand: "Dyson",
    offer: 10,
  },
  {
    id: 33,
    name: "Wooden Coffee Table",
    type: "furniture",
    price: 7000,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "brown",
    material: "wood",
    brand: "Ikea",
    offer: 20,
  },
  {
    id: 34,
    name: "Philips Mixer Grinder",
    type: "appliances",
    price: 6000,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "white",
    material: "metal",
    brand: "Philips",
    offer: 30,
  },
  {
    id: 35,
    name: "Casio Keyboard",
    type: "electronics",
    price: 15000,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "black",
    material: "plastic",
    brand: "Casio",
    offer: 25,
  },
  {
    id: 36,
    name: "Bajaj Ceiling Fan",
    type: "appliances",
    price: 4000,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "white",
    material: "metal",
    brand: "Bajaj",
    offer: 20,
  },
  {
    id: 37,
    name: "Wooden Wardrobe",
    type: "furniture",
    price: 35000,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "brown",
    material: "wood",
    brand: "Durian",
    offer: 40,
  },
  {
    id: 38,
    name: "Nike Sports Cap",
    type: "cloth",
    price: 800,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "black",
    material: "cotton",
    brand: "Nike",
    offer: 15,
  },
  {
    id: 39,
    name: "Panasonic AC",
    type: "appliances",
    price: 42000,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "white",
    material: "metal",
    brand: "Panasonic",
    offer: 20,
  },
  {
    id: 40,
    name: "Samsung Tablet",
    type: "electronics",
    price: 25000,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "grey",
    material: "metal",
    brand: "Samsung",
    offer: 15,
  },
  {
    id: 41,
    name: "LG Soundbar",
    type: "electronics",
    price: 18000,
    image: "https://placehold.co/300x200",
    review: 4,
    color: "black",
    material: "plastic",
    brand: "LG",
    offer: 20,
  },
  {
    id: 42,
    name: "Colgate Toothpaste",
    type: "cleaning",
    price: 200,
    image: "https://placehold.co/300x200",
    review: 5,
    color: "white",
    material: "paste",
    brand: "Colgate",
    offer: 5,
  }
];
